In [2]:
import torch
clap_clip = './checkpoints/clap_clip_native.pt'
clap_clip = torch.load(clap_clip, map_location='cpu')
print(clap_clip.keys())

odict_keys(['Head_A.mlp1.net1.0.weight', 'Head_A.mlp1.net1.0.bias', 'Head_A.mlp1.net1.1.weight', 'Head_A.mlp1.net1.1.bias', 'Head_A.mlp1.net1.1.running_mean', 'Head_A.mlp1.net1.1.running_var', 'Head_A.mlp1.net1.1.num_batches_tracked', 'Head_A.mlp1.net2.0.weight', 'Head_A.mlp1.net2.0.bias', 'Head_A.mlp1.net2.1.weight', 'Head_A.mlp1.net2.1.bias', 'Head_A.mlp1.net2.1.running_mean', 'Head_A.mlp1.net2.1.running_var', 'Head_A.mlp1.net2.1.num_batches_tracked', 'Head_B.mlp1.net1.0.weight', 'Head_B.mlp1.net1.0.bias', 'Head_B.mlp1.net1.1.weight', 'Head_B.mlp1.net1.1.bias', 'Head_B.mlp1.net1.1.running_mean', 'Head_B.mlp1.net1.1.running_var', 'Head_B.mlp1.net1.1.num_batches_tracked', 'Head_B.mlp1.net2.0.weight', 'Head_B.mlp1.net2.0.bias', 'Head_B.mlp1.net2.1.weight', 'Head_B.mlp1.net2.1.bias', 'Head_B.mlp1.net2.1.running_mean', 'Head_B.mlp1.net2.1.running_var', 'Head_B.mlp1.net2.1.num_batches_tracked'])


In [3]:
from copy import deepcopy
adj_pt = deepcopy(clap_clip)
for k in list(adj_pt.keys()):
    adj_k = k[:6] + k[11:]
    adj_pt[adj_k] = adj_pt.pop(k)
    
print(adj_pt.keys())

odict_keys(['Head_A.net1.0.weight', 'Head_A.net1.0.bias', 'Head_A.net1.1.weight', 'Head_A.net1.1.bias', 'Head_A.net1.1.running_mean', 'Head_A.net1.1.running_var', 'Head_A.net1.1.num_batches_tracked', 'Head_A.net2.0.weight', 'Head_A.net2.0.bias', 'Head_A.net2.1.weight', 'Head_A.net2.1.bias', 'Head_A.net2.1.running_mean', 'Head_A.net2.1.running_var', 'Head_A.net2.1.num_batches_tracked', 'Head_B.net1.0.weight', 'Head_B.net1.0.bias', 'Head_B.net1.1.weight', 'Head_B.net1.1.bias', 'Head_B.net1.1.running_mean', 'Head_B.net1.1.running_var', 'Head_B.net1.1.num_batches_tracked', 'Head_B.net2.0.weight', 'Head_B.net2.0.bias', 'Head_B.net2.1.weight', 'Head_B.net2.1.bias', 'Head_B.net2.1.running_mean', 'Head_B.net2.1.running_var', 'Head_B.net2.1.num_batches_tracked'])


In [4]:
torch.save(adj_pt, './checkpoints/clap_clip.pt')

In [5]:
import torch
ulip_clip = './checkpoints/ulip_clip.pt'
ulip_clip = torch.load(ulip_clip, map_location='cpu')
print(ulip_clip.keys())

odict_keys(['CLIP_proj.net.0.weight', 'CLIP_proj.net.0.bias', 'CLIP_proj.net.1.weight', 'CLIP_proj.net.1.bias', 'CLIP_proj.net.1.running_mean', 'CLIP_proj.net.1.running_var', 'CLIP_proj.net.1.num_batches_tracked', 'CLAP_proj.net.0.weight', 'CLAP_proj.net.0.bias', 'CLAP_proj.net.1.weight', 'CLAP_proj.net.1.bias', 'CLAP_proj.net.1.running_mean', 'CLAP_proj.net.1.running_var', 'CLAP_proj.net.1.num_batches_tracked'])


In [6]:
from copy import deepcopy
adj_pt = deepcopy(ulip_clip)
for k in list(adj_pt.keys()):
    if 'CLIP_proj' == k[:9]:
        adj_k = 'Head_A' + k[9:]
        adj_pt[adj_k] = adj_pt.pop(k)
    
    if 'CLAP_proj' == k[:9]:
        adj_k = 'Head_B' + k[9:]
        adj_pt[adj_k] = adj_pt.pop(k)
    
print(adj_pt.keys())

odict_keys(['Head_A.net.0.weight', 'Head_A.net.0.bias', 'Head_A.net.1.weight', 'Head_A.net.1.bias', 'Head_A.net.1.running_mean', 'Head_A.net.1.running_var', 'Head_A.net.1.num_batches_tracked', 'Head_B.net.0.weight', 'Head_B.net.0.bias', 'Head_B.net.1.weight', 'Head_B.net.1.bias', 'Head_B.net.1.running_mean', 'Head_B.net.1.running_var', 'Head_B.net.1.num_batches_tracked'])


In [ ]:
torch.save(adj_pt, './checkpoints/ulip_clip_adj.pt')

tensor([-0.0531,  0.0346,  0.0672, -0.0167,  0.0574], device='cuda:3')
tensor([ 0.0197, -0.0725, -0.0017,  0.0762, -0.0025], device='cuda:3')
tensor([ 0.0374,  0.0330, -0.0656, -0.0490, -0.0650], device='cuda:3')